version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:

      - DATABASE_URL=postgresql+psycopg2://user:postgres@db:5432/user
    depends_on:
      - db

    volumes:
      - ./:/app
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'user'
    ports:
      - "5432:5432"   
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:

